import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/Navbar";
import Sidebar from "./_components/Sidebar";
import NavbarWrapper from "./_components/NavbarWrapper";
import AppNav from "./_components/AppNav";
import { Toaster } from "react-hot-toast";
import AppNavWrapper from "./_components/AppNavWrapper";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Spendify",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-[var(--background)] h-screen w-full antialiased transition-all duration-300 ease-in-out`}
      >
        <main className=" h-full flex flex-col w-full border-white">
          <AppNavWrapper />
          <Toaster toastOptions={{ position: "top-right" }} />
          <div className="">
            <NavbarWrapper />
            <main className="overflow-auto h-full">{children}</main>
          </div>
        </main>
      </body>
    </html>
  );
}