import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/Navbar";
import Sidebar from "./_components/Sidebar";
import NavbarWrapper from "./_components/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Spendify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-[var(--background)] h-screen w-full antialiased`}
      >
        <NavbarWrapper />
        <main className="lg:pt-20 pt-16 h-full w-full border-white">{children}</main>
      </body>
    </html>
  );
}